development:
   adapter: mysql
   database: niezapp
   username: root
   password: AK@3693
   host: localhost

test:
   adapter: mysql
   database: niezapp
   username: root
   password: AK@3693
   host: localhost

production:
   adapter: mysql
   database: niezapp
   username: root
   password: AK@3693
   host: localhost
